# Generated by Django 3.0.5 on 2023-03-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='admin_comment',
            new_name='agent_comment',
        ),
    ]
