# Generated by Django 3.0.5 on 2023-03-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20230320_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='aadhar',
            field=models.CharField(default=None, max_length=12,null=True),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='vechileno',
            field=models.CharField(default=None, max_length=10,null=True),
        ),
    ]
