# Generated by Django 3.0.5 on 2023-03-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20230320_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyrecord',
            name='aadhar',
        ),
    ]
