# Generated by Django 3.0.5 on 2023-03-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_policyrecord_aadhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyrecord',
            name='aadhar',
        ),
    ]
