# Generated by Django 3.0.5 on 2023-03-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_remove_policyrecord_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='aadhar',
            field=models.CharField(default=0, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='policyrecord',
            name='vechileno',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
