# Generated by Django 3.0.5 on 2023-03-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_auto_20230320_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrecord',
            name='vechileno',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
