# Generated by Django 3.0.5 on 2023-03-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_auto_20230320_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyrecord',
            old_name='vechileno',
            new_name='vechile',
        ),
    ]
