# Generated by Django 3.0.5 on 2023-03-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_auto_20230320_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrecord',
            name='aadhar',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='policyrecord',
            name='vechile',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
