# Generated by Django 3.0.5 on 2023-03-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0016_auto_20230321_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyrecord',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='policyrecord',
            name='vechile',
        ),
    ]
