# Generated by Django 3.0.5 on 2023-03-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20230328_2145'),
        ('insurance', '0017_auto_20230324_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('vehicle1', models.CharField(default=None, max_length=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
