# Generated by Django 3.0.5 on 2023-03-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0018_vehicle1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle1',
            old_name='vehicle1',
            new_name='vehicle_no',
        ),
    ]
