# Generated by Django 3.0.5 on 2023-03-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_auto_20230329_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle1',
            name='year',
            field=models.PositiveIntegerField(default=1998),
            preserve_default=False,
        ),
    ]
