# Generated by Django 3.0.5 on 2023-03-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0020_vehicle1_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle1',
            name='year',
        ),
    ]
