# Generated by Django 3.0.5 on 2023-03-29 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0021_remove_vehicle1_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='vehicle',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='insurance.Vehicle1'),
            preserve_default=False,
        ),
    ]
