# Generated by Django 3.0.5 on 2023-03-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0022_policyrecord_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyrecord',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='vehicle_id',
            field=models.IntegerField(default=0),
        ),
    ]
