# Generated by Django 3.0.5 on 2023-03-19 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='house',
            field=models.CharField(default='helo', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='kerala', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='illikunnu', max_length=40),
            preserve_default=False,
        ),
    ]
