# Generated by Django 3.0.5 on 2023-03-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230319_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agent_code',
            field=models.CharField(default='5aefa', max_length=5),
            preserve_default=False,
        ),
    ]
