# Generated by Django 3.0.5 on 2023-03-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_agent_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhar',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vechile',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
