# Generated by Django 3.0.5 on 2023-03-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20230323_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar',
            field=models.CharField(default='NA', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vechile',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
    ]
