# Generated by Django 3.0.5 on 2023-03-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20230323_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='vechile',
            new_name='vehicle',
        ),
    ]
