# Generated by Django 3.0.5 on 2023-03-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20230323_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
