# Generated by Django 3.0.5 on 2023-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20230323_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
