# Generated by Django 3.0.5 on 2023-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20230324_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
