# Generated by Django 3.0.5 on 2023-04-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20230328_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='vehicle',
        ),
    ]
